# File: CompileALApps.yml

parameters:
  Auth: 'Windows'
  CertFile: ''
  CertPwd: ''
  CertSecret: ''
  ConfigFolder: $($env:AGENT_BUILDDIRECTORY)
  ContainerName: 'BC'
  ImageName: 'microsoft/bcsandbox'
  LicenseFile: ''
  UserPwd: ''

steps:
- powershell: |
   Import-Module NVRAppDevOps -DisableNameChecking
   Import-Module navcontainerhelper -DisableNameChecking
   Write-Host $env:ConfigFolder
   if(!([String]::IsNullOrEmpty($env:CertFile)) -and (!([String]::IsNullOrEmpty($env:CertSecret))))
   {
     Write-Error "You can only specify CertFile or CertSecret not both at the same time."
     exit 1
   }
   if($env:CertSecret)
   {
    $TmpFile = (New-TemporaryFile | Rename-Item -NewName { $_ -replace 'tmp$', 'pfx' } -PassThru).Fullname
    $pfxUnprotectedBytes = [Convert]::FromBase64String($env:CertSecret)
    $pfx = New-Object Security.Cryptography.X509Certificates.X509Certificate2
    $pfx.Import($pfxUnprotectedBytes, $null, [Security.Cryptography.X509Certificates.X509KeyStorageFlags]::Exportable)
    $pfxProtectedBytes = $pfx.Export([Security.Cryptography.X509Certificates.X509ContentType]::Pkcs12, $env:CertPwd)
    [IO.File]::WriteAllBytes($TmpFile, $pfxProtectedBytes)
   }

   $Configuration = New-Object -Typename psobject
   Add-Member -InputObject $Configuration -MemberType Noteproperty -Name "ContainerName" -Value $env:ContainerName
   Add-Member -InputObject $Configuration -MemberType Noteproperty -Name "ImageName" -Value $env:ImageName
   Add-Member -InputObject $Configuration -MemberType Noteproperty -Name "LicenseFile" -Value $env:LicenseFile
   Add-Member -InputObject $Configuration -MemberType Noteproperty -Name "CertFile" -Value $TmpFile
   Add-Member -InputObject $Configuration -MemberType Noteproperty -Name "CertPwd" -Value $env:CertPwd
   Add-Member -InputObject $Configuration -MemberType Noteproperty -Name "Username" -Value $env:Username
   Add-Member -InputObject $Configuration -MemberType Noteproperty -Name "Password" -Value $env:UserPwd
   Add-Member -InputObject $Configuration -MemberType Noteproperty -Name "Auth" -Value $env:Auth
   Write-Host $Configuration

   $Configuration | ConvertTo-Json -Depth 100 | Out-File (-join($env:ConfigFolder,"\config.json")) -Force

  displayName: 'Ensure AL Config'
  env:
    Auth: ${{ parameters.Auth }}
    CertFile: ${{ parameters.CertFile }}
    CertPwd: ${{ parameters.CertPwd }}
    CertSecret: ${{ parameters.CertSecret }}
    ConfigFolder: ${{ parameters.ConfigFolder }}
    ContainerName: ${{ parameters.ContainerName }}
    ImageName: ${{ parameters.ImageName }}
    LicenseFile: ${{ parameters.LicenseFile }}
    UserPwd: ${{ parameters.UserPwd }}
